# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1teISZ82ZNBl2aNKvXM6tq33zf_QwpCP1
"""

import random
# used to let computer pick randomly

print("Welcome to Rock Paper Scissors Game")

# list of possible choices
choices = ["rock", "paper", "scissors"]

# function to take input from user
def get_user_choice():
    while True:
        user = input("Enter rock, paper or scissors: ").lower().strip()

        # check if user entered correct option
        if user in choices:
            return user

        # if wrong input, ask again
        print("Invalid input! Try again")


# function to decide winner of one round
def get_winner(user, computer):

    # if both chose same → draw
    if user == computer:
        return "draw"

    # all winning conditions for user
    elif (user == "rock" and computer == "scissors") or \
         (user == "paper" and computer == "rock") or \
         (user == "scissors" and computer == "paper"):
        return "user"

    # otherwise computer wins
    else:
        return "computer"


# function to play multiple rounds
def play_round():
    user_score = 0
    computer_score = 0
    max_rounds = 5   # total rounds limit
    current_round = 0

    # loop for rounds
    while current_round < max_rounds:
        current_round += 1

        print("\n==============================")
        print(f"Round {current_round} of {max_rounds}")
        print("==============================")

        # get user and computer choices
        user = get_user_choice()
        computer = random.choice(choices)
        print("Computer chose:", computer)

        # check result
        result = get_winner(user, computer)

        if result == "draw":
            print("It's a draw")

        elif result == "user":
            print("YOU WIN THIS ROUND!")
            user_score += 1  # increase user score

        else:
            print("You lost this round!")
            computer_score += 1  # increase computer score

        # show current score
        print(f"Score -> You: {user_score} | Computer: {computer_score}")

        # if anyone reaches 3 → game ends early
        if user_score == 3 or computer_score == 3:
            break

    return user_score, computer_score


# main game function
def play_game():
    while True:
        # play one full match
        user_score, computer_score = play_round()

        print("\nGAME OVER")
        print(f"Your Score: {user_score}")
        print(f"Computer Score: {computer_score}")

        # decide final winner
        if user_score > computer_score:
            print("CONGRATULATIONS! YOU WON THE MATCH!")

        elif computer_score > user_score:
            print("COMPUTER WON THE MATCH!")

        else:
            print("MATCH DRAW!")

        # ask user if they want to play again
        restart = input("\nDo you want to play again? (yes/no): ").lower().strip()

        if restart != "yes":
            print("Thanks for playing! See you again")
            break


# start the game
play_game()